# Generated by Django 4.2.29 on 2026-03-16 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeafDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('predicted_disease', models.CharField(blank=True, max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('local_model', 'Local Model'), ('gemini_api', 'Gemini API')], default='local_model', max_length=20)),
                ('treatment_guidance', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaf_diagnosis_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
