# Generated by Django 6.0.2 on 2026-03-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_leafdiagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafdiagnosis',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
