# Generated by Django 4.2.29 on 2026-03-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_leafdiagnosis_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='leafdiagnosis',
            name='plant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
