# Generated by Django 5.0.3 on 2026-04-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_leafdiagnosis_plant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='name_ml',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name (Malayalam)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_ml',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name (Malayalam)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='preventive_measures_ml',
            field=models.TextField(blank=True, verbose_name='Prevention (Malayalam)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms_ml',
            field=models.TextField(blank=True, verbose_name='Symptoms (Malayalam)'),
        ),
        migrations.AddField(
            model_name='disease',
            name='treatment_recommendations_ml',
            field=models.TextField(blank=True, verbose_name='Treatment (Malayalam)'),
        ),
    ]
