# Generated by Django 5.0.3 on 2026-04-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_membershipprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipprofile',
            name='request_status',
            field=models.CharField(choices=[('none', 'No Request'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='membershipprofile',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
